name: ci
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm

      - name: npm-install
        run: npm i

      - name: app-build
        run: npm run build
        
      - name: lint-code
        run: npm run lint
