name: CI
on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 24.5.0
          cache: pnpm

      - name: install pnpm
        run: npm install -g pnpm

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: app-build
        run: pnpm run build
        
      - name: lint-code
        run: pnpm run lint
      
      - name: prettier-code
        run: pnpm run prettier

      - name: jest-testing
        run: pnpm run test:ci
        
      - name: "upload test-results"
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: test-results/jest-junit.xml
