name: CI
on:
  push:
    branches: [ main ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: npm

      - name: npm-install
        run: npm i

      - name: app-build
        run: npm run build
        
      - name: lint-code
        run: npm run lint
      
      - name: prettier-code
        run: npm run prettier

      - name: jest-testing
        run: npm run test:ci
        
      - name: "upload test-results"
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: test-results/jest-junit.xml
